"""
The fibonacci sequence is a sequence where each term is generated by adding up the 2 previous terms. The fibonacci sequence can start with (1, 1) or (0, 1). In this test we assume it starts with (1, 1) For example, up to the 10th term:

1, 1, 2, 3, 5, 8, 13, 21, 34, 55...

Your function must return the nth term of the sequence.
"""

def fib(n):
    if n in [0, 1]:
        return n
    return fib(n - 1) + fib(n - 2)
